### ISSUE TITLE
Cannot build with G+Smo v26.09.0

### ISSUE THREAD

**Issue by MakisH** [gismo/gsPreCICE#27]
Building with https://github.com/gismo/gismo/tree/v26.09.0, I am getting:

```
gismo/optional/gsPreCICE/examples/perpendicular-flap-vertex-gismo.cpp:373:9: error: 'collection' was not declared in this scope
373 |         collection.save();
    |         ^~~~~~~~~~
```
